### ISSUE TITLE
Proposal: rename “neko” command to “mine”

### ISSUE THREAD

**Issue by dahlia** [nekoyume/nekoyume#105]
The `nekoyume neko` command runs a block miner, but it is less likely to guess what it does.  There are two assumptions behind the naming that, 1. people knows “neko” means cat in Japanese, and 2. people knows cat's dreaming is block mining in the Nekoyume world.  I find it's somewhat obfuscated, so suggest to add a new `nekoyume mine` command instead and deprecate the existing `nekoyume neko` command.

**Comment by jckdotim** [comment]
Approve :+1:
