### ISSUE TITLE
Proposal: No private key/ public key store or signing process for transactions WTF

### ISSUE THREAD

**Issue by hskang9** [nekoyume/nekoyume#46]
So I see command line option here generate private/public key eh?

but I do not see the server handling the transaction signing/ or anything like that.

This is pretty serious issue because **everyone can be everyone**

for writing a block to ledger you need to sign a transaction to verify that is is generated from **oneself**

## Example
transaction #1:
{
    sender: "address which is generated from user's public key(ethereum way) or public key"
    recipient: "same thing from sender"
    amount : <amount of your gold whatever>
    blockHash: <generated hash>
    certificate: <certificate generated from user's private key>
}

## Verification
1. Get sender's public key from sender's address
2. See if decrypted hash string matches blockHash when the certificate is decrypted by public key
3. Add transaction to the block
 
I do not think you guys should call this a blockchain if you cannot give self-identity to users for processing a transaction. 

Loopchain just put this with [TODO] and call it as a blockchain. Same bullshit that you guys are doing while giving away insecure tokens on airdrop.

**Comment by jckdotim** [comment]
Hi. I don't understand what you are saying. Can you visit our telegram and explain in more detail?

**Comment by dahlia** [comment]
[Transactions (i.e., `Move`) are signed.](https://github.com/nekoyume/nekoyume/blob/49be7b35dc3b5e84401a6b16f36ede6a9e4ecce5/nekoyume/models.py#L1023-L1036)

**Comment by dahlia** [comment]
Plus, please don't be rude.  Founding vulnerability does not allow you to be rude to others.

**Comment by hskang9** [comment]
Well sorry but I thought private/pubic key is pretty serious stuff to discuss. It is not a vulnerability. It is a building **component** for blockchain. I just can't take it yknow

**Comment by hskang9** [comment]
@dahlia I know it is signed but I want to know a verification process before adding a transaction to a block. Can you refer the code please.

**Comment by dahlia** [comment]
[Well, transaction signatures (i.e., `Move.signature`) are verified (or rather falsified) as well][1], since it's the purpose of signing them.

[1]: https://github.com/nekoyume/nekoyume/blob/49be7b35dc3b5e84401a6b16f36ede6a9e4ecce5/nekoyume/models.py#L513-L533

**Comment by jckdotim** [comment]
@hskang9 Our telegram channel can speak Korean if you want. 텔레그램 채널에서는 한국어로 편하게 논의하셔도 좋습니다.

**Comment by hskang9** [comment]
Ok I see now how it works I will just see how I can refactor. Sorry for being rude.
