### ISSUE TITLE
Prevent hack&slash when the player is already dead

### ISSUE THREAD

**Issue by jckdotim** [nekoyume/nekoyume#52]

**Comment by leekchan** [comment]
(Discussion)
Now the concept of **dead** does not exist, so the implementation goal could be ambiguous. 

According to the dungeon world rule...
```A character who is reduced to 0 HP immediately takes his Last Breath. ... (ellipsis) ... Depending on the outcome of the Last Breath the character may become stable. A stable character stays at 0 HP but is alive and unconscious. If they receive healing they regain consciousness and may return to battle or seek safety. ```
 
So, in my opinion, if HP becomes zero, preventing all actions except sleeping could be a good first step. (+ preventing HP from becoming negative)

The `Last Breath` stage & receiving healing from other players could be implemented in the future.

@jckdotim What do you think?

**Comment by ipdae** [comment]
can i try this issue?
