### ISSUE TITLE
Guide for Ubuntu

### ISSUE THREAD

**Issue by jckdotim** [nekoyume/nekoyume#56]

**Comment by josephlee518** [comment]
**Ubuntu 문서 작성**과 동시에 [Vagrantfile](https://www.vagrantup.com/docs/vagrantfile/) 도 한번 작성해볼려고 합니다.

**Comment by josephlee518** [comment]
I Think There is No Need To Document about running nekoyume on ubuntu :smile:

**Comment by jckdotim** [comment]
Thank you for checking. :) I'll close this issue.
