### ISSUE TITLE
Proposal: Using `venv` instead of `virtualenv`

### ISSUE THREAD

**Issue by sconeman** [nekoyume/nekoyume#98]
I propose to use `venv` instead of `virtualenv`.

Using [python3 -m venv](https://docs.python.org/3/library/venv.html) instead of virtualenv is recommended by the standard documentation.

And If you create an environment with `virtualenv` in Python 3.6, and then upgrade to Python 3.7, the virtualenv is broken because you know longer have the shared libraries Python needs. Using `venv` you can just run python3 -m venv --upgrade.

**Comment by sconeman** [comment]
@jckdotim If you accept this, I will create the PR :)

**Comment by jckdotim** [comment]
I think your suggestion is right. Please edit README to use `venv`. Thank you.
